import test from 'node:test';
import assert from 'node:assert/strict';
import { normalize,symbolFor,fetchFundamentals } from '../lib/providers/eodhd.js';
import { createHandler } from '../lib/providers/eodhd-handler.js';
function payload(code='MSFT') {return {General:{Code:code,Exchange:'NASDAQ',CurrencyCode:'USD',UpdatedAt:'2026-10-07'},Highlights:{ProfitMargin:0.4031,OperatingMarginTTM:0.45,ReturnOnEquityTTM:1.1721,QuarterlyRevenueGrowthYOY:1.059,QuarterlyEarningsGrowthYOY:-0.2,PEGRatio:null},Valuation:{ForwardPE:'25.12',PriceSalesTTM:11.8},AnalystRatings:{TargetPrice:585.6},Financials:{Income_Statement:{currency_symbol:'BRL',quarterly:{past:{date:'2026-06-30',filing_date:'2026-07-29',currency_symbol:'BRL',netIncome:'10',totalRevenue:'100'},future:{date:'2026-09-30',filing_date:'2026-11-04',netIncome:null,totalRevenue:null}}}},Earnings:{History:{future:{date:'2026-09-30',reportDate:'2026-11-04',epsActual:null},past:{date:'2026-06-30',reportDate:'2026-07-29',epsActual:1}}}};}
const options={retrievedAt:'2026-10-07T19:00:00Z',sample:true};
test('maps NCI share class and rejects symbols outside the reviewed universe',()=>{assert.equal(symbolFor('BRK.B'),'BRK-B.US');assert.equal(symbolFor('INTR'),'INTR.US');assert.throws(()=>symbolFor('MSFT.US'));assert.throws(()=>symbolFor('../MSFT'));});
test('preserves decimal ratios, growth above 100%, losses and missing PEG',()=>{const row=normalize('MSFT',payload(),options);assert.equal(row.data.profitMargin,0.4031);assert.equal(row.data.returnOnEquity,1.1721);assert.equal(row.data.revenueGrowthYoY,1.059);assert.equal(row.data.earningsGrowthYoY,-0.2);assert.equal(row.data.peg,null);assert.equal(row.data.forwardPE,25.12);assert.deepEqual(row.validation.missingMetrics,['peg']);assert.equal(row.validation.mode,'SAMPLE_ONLY');assert.equal(row.validation.decisionAuthorization,false);});
test('separates reported period, release, retrieval and currencies; ignores future estimates',()=>{const row=normalize('MSFT',payload(),options);assert.equal(row.provenance.sourcePeriodEnd,'2026-06-30');assert.equal(row.provenance.sourcePublishedAt,'2026-07-29');assert.equal(row.provenance.reportingCurrency,'BRL');assert.equal(row.provenance.currency,'USD');assert.equal(row.provenance.providerUpdatedAt,'2026-10-07');assert.equal(row.provenance.sampleOnly,true);});
test('missing statements never borrow a period from estimates or update date',()=>{const raw=payload();delete raw.Financials;assert.equal(normalize('MSFT',raw,options).provenance.sourcePeriodEnd,null);});
test('rejects wrong instrument; never coerces null, boolean or empty metrics to zero',()=>{assert.throws(()=>normalize('NVDA',payload(),options));const raw=payload();raw.Highlights.ProfitMargin=false;raw.Valuation.ForwardPE=' ';raw.AnalystRatings.TargetPrice=-1;const row=normalize('MSFT',raw,options);assert.equal(row.data.profitMargin,null);assert.equal(row.data.forwardPE,null);assert.equal(row.data.analystTargetPrice,null);});
test('provider request keeps credentials out of normalized payload and uses a timeout',async()=>{const row=await fetchFundamentals('MSFT','test-secret',{retrievedAt:options.retrievedAt,fetchImpl:async(url,config)=>{assert.equal(url.hostname,'eodhd.com');assert.equal(url.searchParams.get('api_token'),'test-secret');assert.ok(config.signal);assert.equal(config.redirect,'error');return {ok:true,json:async()=>payload()};}});assert.ok(!JSON.stringify(row).includes('test-secret'));});
test('classifies provider access, rate limits and invalid JSON without exposing response bodies',async()=>{for(const [status,code] of [[403,'PROVIDER_ACCESS_DENIED'],[429,'PROVIDER_RATE_LIMIT'],[500,'PROVIDER_UNAVAILABLE']])await assert.rejects(fetchFundamentals('MSFT','secret',{fetchImpl:async()=>({ok:false,status})}),{code});await assert.rejects(fetchFundamentals('MSFT','secret',{fetchImpl:async()=>({ok:true,json:async()=>{throw new Error('secret');}})}),{code:'PROVIDER_INVALID_PAYLOAD'});});
async function call({subject='owner',authError,env={},method='GET',symbol='MSFT'}={}) {let calls=0;const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.statusCode=v;return this;},json(v){this.body=v;return this;}};await createHandler({env,authenticate:async()=>{if(authError)throw authError;return {subject};},load:async()=>{calls++;return normalize('MSFT',payload(),options);}})({method,query:{symbol}},res);return {...res,calls};}
const enabled={EODHD_OWNER_SUBJECT:'owner',EODHD_PREVIEW_ENABLED:'true',EODHD_API_KEY:'secret'};
test('unauthenticated and non-owner clients cannot fetch provider data',async()=>{const a=await call({authError:{code:'NCI_AUTH_REQUIRED',httpStatus:401},env:enabled});assert.equal(a.statusCode,401);assert.equal(a.calls,0);const b=await call({subject:'other',env:enabled});assert.equal(b.statusCode,403);assert.equal(b.calls,0);assert.equal(b.headers['Cache-Control'],'private, no-store');});
test('missing owner, disabled mode or missing key make no paid API calls',async()=>{for(const env of [{},{...enabled,EODHD_PREVIEW_ENABLED:'false'},{...enabled,EODHD_API_KEY:''}])assert.equal((await call({env})).calls,0);});
test('only owner GET for an approved symbol can fetch; private response cannot authorize decisions',async()=>{const good=await call({env:enabled});assert.equal(good.statusCode,200);assert.equal(good.calls,1);assert.equal(good.body.decisionAuthorization,false);assert.equal(good.body.writeOperationsEnabled,false);for(const args of [{method:'POST'},{symbol:'VOO'}])assert.equal((await call({...args,env:enabled})).calls,0);});
